# Generated by Django 2.2.12 on 2021-01-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('number', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'people',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Timing',
            fields=[
                ('mykey', models.AutoField(primary_key=True, serialize=False)),
                ('entry', models.DateTimeField()),
                ('leaving', models.DateTimeField()),
            ],
            options={
                'db_table': 'timing',
                'managed': False,
            },
        ),
    ]
