# Generated by Django 2.2.12 on 2021-01-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(verbose_name='Start')),
                ('end', models.DateField(blank=True, null=True, verbose_name='End')),
                ('opening', models.TimeField(verbose_name='Opening every day')),
                ('closing', models.TimeField(verbose_name='Closing every day')),
            ],
            options={
                'verbose_name': 'Exhibition',
                'verbose_name_plural': 'Exhibitions',
            },
        ),
    ]
